model_params:
  name: 'semVAE'
  in_channels: 3
  #latent_dim: 128
  latent_dim: 128
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

data_params:
  data_path: "/nfs/h1/userhome/wdh-llx/workingdir/zsk/sVAE/Data/Data/"
  train_batch_size: 64
  val_batch_size:  64
  #patch_size: 64
  patch_size: 128
  num_workers: 4
  
exp_params:
  #LR: 0.005
  #LR: 0.0001
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/face3d/"
  manual_seed: 1265
  name: 'BetaVAE'
